---
title: "Final Report"
subtitle: "A description of EVR628 data visualization project"
author: "Jeynaliz Ortiz Gonzalez"
format:
  html:
    toc: true
execute:
  message: false
---

# Introduction

This project contains data relevant to sea turtle hatchling disorientations at
the moment of emergence for the 2025 year. Data showcases all disorientations in
beaches located within 5 sites: Key Biscayne, Fisher Island, Miami Beach, 
Haulover, and Golden Beach. 

# Objective(s)


# Data sources

The data used in this project has been collected by authorized sea turtle 
personnel (permit MTP 150) from the Miami-Dade County Parks Sea Turtle 
Conservation Program. This singular dataset pertains to all nest hatches across
multiple survey areas during the 2025 nesting season. 

Variables included in this data:

Raw data: date, nest, species, latitude, longitude, direction, disoriented
Clean data: date, nest, latitude, longitude, direction, disoriented, sites

# Data processing 


# Main findings 


# References

Appelhans T, Detsch F, Reudenbach C, Woellauer S (2025). _mapview:
  Interactive Viewing of Spatial Data in R_.
  doi:10.32614/CRAN.package.mapview
  <https://doi.org/10.32614/CRAN.package.mapview>, R package version
  2.11.4, <https://CRAN.R-project.org/package=mapview>.

Florida Department of Transportation. (2019). Detailed Florida state boundary.
  Retrieved December 2, 2025 from   
  https://gis-fdot.opendata.arcgis.com/datasets/fdot::detailed-florida-state-boundary/about
  
H. Wickham. ggplot2: Elegant Graphics for Data Analysis.
  Springer-Verlag New York, 2016.
  
Pebesma, E., & Bivand, R. (2023). Spatial Data Science: With
  Applications in R. Chapman and Hall/CRC.
  https://doi.org/10.1201/9780429459016

Pebesma, E. (2018). Simple Features for R: Standardized Support for
  Spatial Vector Data. The R Journal 10 (1), 439-446.
  https://doi.org/10.32614/RJ-2018-009
  
Pedersen T (2025). _patchwork: The Composer of Plots_.
  doi:10.32614/CRAN.package.patchwork
  <https://doi.org/10.32614/CRAN.package.patchwork>, R package version
  1.3.2, <https://CRAN.R-project.org/package=patchwork>.
  
R Core Team (2025). _R: A Language and Environment for Statistical
  Computing_. R Foundation for Statistical Computing, Vienna, Austria.
  <https://www.R-project.org/>.
  
  
